# Generated by Django 3.1.7 on 2021-03-22 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMC', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namemodality', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespecialty', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=2)),
                ('hour', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.city')),
            ],
        ),
    ]
