# Generated by Django 3.1.7 on 2021-03-22 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotes',
            name='medical_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.medical_center'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.modality'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.specialty'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
